import {
  BadgePercent,
  BarChart3,
  BookOpen,
  Building2,
  Camera,
  ClipboardList,
  Contact,
  Database,
  Filter,
  Folder,
  Globe,
  Grid3x3,
  LayoutTemplate,
  Link as LinkIcon,
  Mail,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Package,
  Plug,
  QrCode,
  Receipt,
  Settings,
  ShoppingCart,
  Smartphone,
  Smile,
  Store,
  Target,
  Upload,
  Users,
  Workflow,
  Wrench,
  type LucideIcon
} from 'lucide-react'

/**
 * Registry explícito em vez de import dinâmico do lucide inteiro: só entra no
 * bundle o ícone que o conteúdo realmente usa. Nome desconhecido quebra o
 * `content:check`, então o fallback aqui nunca deveria aparecer em produção.
 */
export const CONTENT_ICONS: Record<string, LucideIcon> = {
  'badge-percent': BadgePercent,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  'building-2': Building2,
  camera: Camera,
  'clipboard-list': ClipboardList,
  contact: Contact,
  database: Database,
  filter: Filter,
  folder: Folder,
  globe: Globe,
  'grid-3x3': Grid3x3,
  'layout-template': LayoutTemplate,
  link: LinkIcon,
  mail: Mail,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  'messages-square': MessagesSquare,
  package: Package,
  plug: Plug,
  'qr-code': QrCode,
  receipt: Receipt,
  settings: Settings,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  store: Store,
  target: Target,
  upload: Upload,
  users: Users,
  workflow: Workflow,
  wrench: Wrench
}
